### ISSUE TITLE
Setting the value of a ReadOnly variable logic

### ISSUE THREAD

**Issue by CowboyCoderForever** [ZeShmoutt/Unity-ScriptableVariables#1]
https://github.com/ZeShmoutt/Unity-ScriptableVariables/blob/683ce8c5c3d828bac010ef60af037bbd9e808970/ZeShmouttsAssets/ScriptableVariables/Scripts/ScriptableVariable.cs#L102

I think your readonly logic is backwards in your setter function.  Shouldn't it be `if (!readOnly) {..` ?

**Comment by ZeShmoutt** [comment]
Sorry for the ridiculous delay, I just didn't get any mail or message with your issue and completely missed it.

Fixed in v1.1.
